services:
  dev:
    image: ${IMAGE_NAME:?Set in .env}
    env_file:
      - .env
    environment:
      - GIT_TOKEN_FILE=${GIT_TOKEN_FILE:-/run/secrets/git_token}
      - GIT_REPO=${GIT_REPO:?Set in .env (format: owner/repo)}
      - GIT_BRANCH=${GIT_BRANCH:-main}
      - TARGET_DIR=${TARGET_DIR:-/workspace/repo}
    secrets:
      - git_token
    volumes:
      - ./workspace:/workspace:rw
      - ./secure-clone.sh:/workspace/secure-clone.sh:ro
      - ~/.gitconfig:/home/devuser/.gitconfig:ro
      - ~/.ssh:/home/devuser/.ssh:ro
    command: ["/bin/zsh"]

secrets:
  git_token:
    file: ./secrets/git_token
