services:
  dp-databricks-application:
    image: "${IMAGE_NAME:-}"
    platform: linux/amd64
    environment:
      - IMAGE_NAME="${IMAGE_NAME:-}"
      - GIT_TOKEN_FILE=/run/secrets/git_token
      - GIT_REPO="${GIT_REPO:-}"
      - GIT_BRANCH=main
      - GIT_USERNAME=azdo
      - DOCKERFILE=Dockerfile
      - PROJECT_DIR=/workspace
    secrets:
      - git_token
    volumes:
      - workspace-data:/workspace:rw
    tty: true
    stdin_open: true

secrets:
  git_token:
    file: ./secrets/git_token

volumes:
  workspace-data:
    driver: local
  repo-data:
    driver: local
