services:
  dev:
    image: ${IMAGE_NAME:?Set in .env}
    # Build the image locally (multi-arch friendly Dockerfile). Optionally set
    # 'platform: linux/amd64' or 'platform: linux/arm64' here to force a specific arch.
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - GIT_TOKEN_FILE=${GIT_TOKEN_FILE}
      - GIT_URL=${GIT_URL}
      - GIT_PROVIDER=${GIT_PROVIDER}
      - GIT_HOST=${GIT_HOST}
      - GIT_REPO=${GIT_REPO}
      - GIT_BRANCH=${GIT_BRANCH}
      - TARGET_DIR=${TARGET_DIR}
      - GIT_USERNAME=${GIT_USERNAME}
    secrets:
      - git_token
    volumes:
      - ./workspace:/workspace:rw
    tty: true
    stdin_open: true

secrets:
  git_token:
    file: ./secrets/git_token
