services:
  dev:
    image: ${IMAGE_NAME:-${IMAGE_NAME:-}}
    platform: linux/amd64
    environment:
      - IMAGE_NAME=${IMAGE_NAME:-}
      - GIT_TOKEN_FILE=${GIT_TOKEN_FILE:-/run/secrets/git_token}
      - GIT_URL=${GIT_URL:-}
      - GIT_REPO=${GIT_REPO:-}
      - GIT_REPOS=${GIT_REPOS:-}
      - GIT_BRANCH=${GIT_BRANCH:-main}
      - GIT_PROVIDER=${GIT_PROVIDER:-}
      - GIT_HOST=${GIT_HOST:-}
      - GIT_USERNAME=${GIT_USERNAME:-}
      - GIT_TOKEN=${GIT_TOKEN:-}
      - GIT_FORCE_RECLONE=${GIT_FORCE_RECLONE:-1}
      - DOCKERFILE=${DOCKERFILE:-Dockerfile}
      - PROJECT_DIR=${PROJECT_DIR:-/workspace}
    secrets:
      - git_token
    volumes:
      - workspace-data:/workspace:rw
    tty: true
    stdin_open: true

secrets:
  git_token:
    file: ./secrets/git_token

volumes:
  workspace-data:
    driver: local
